# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u0433\u043e\u0440\u043e\u0434',
                'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u0441\u0442\u0440\u0430\u043d\u0430',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('address', models.CharField(max_length=200, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('comfort', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='\u041a\u043e\u043c\u0444\u043e\u0440\u0442')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.City', verbose_name='\u0413\u043e\u0440\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u0433\u043e\u0441\u0442\u0438\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0413\u043e\u0441\u0442\u0438\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('birthday', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('address', models.CharField(max_length=200, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('phone', models.CharField(max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440',
                'verbose_name_plural': '\u041c\u0435\u043d\u0435\u0434\u0436\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Recource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f')),
                ('date_and_time', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f')),
                ('comments', models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Recource_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0442\u0438\u043f \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0442\u0438\u043f \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Country', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u0440\u0435\u0433\u0438\u043e\u043d',
                'verbose_name_plural': '\u0420\u0435\u0433\u0438\u043e\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u0443\u0440\u0430')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0442\u0443\u0440\u0430')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0442\u0443\u0440\u0430')),
                ('days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='\u0414\u043d\u0435\u0439')),
                ('hotel_price', models.PositiveIntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440')),
                ('tour_price', models.PositiveIntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430 \u0442\u0443\u0440\u0430')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.City', verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Hotel', verbose_name='\u0413\u043e\u0441\u0442\u0438\u043d\u0438\u0446\u0430')),
            ],
            options={
                'verbose_name': '\u0442\u0443\u0440',
                'verbose_name_plural': '\u0422\u0443\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Tour_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('phone', models.CharField(max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('approved', models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0435\u043d\u0438\u0435')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Manager', verbose_name='\u041c\u0435\u043d\u0435\u0434\u0436\u0435\u0440')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel.Tour', verbose_name='\u0412\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0439 \u0442\u0443\u0440')),
            ],
            options={
                'verbose_name': '\u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0442\u0443\u0440\u0430',
                'verbose_name_plural': '\u0411\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u0442\u0443\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Tour_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0422\u0438\u043f \u0442\u0443\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0442\u0438\u043f \u0442\u0443\u0440\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0442\u0443\u0440\u0430',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('phone', models.CharField(max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0442\u0443\u0440\u0438\u0441\u0442',
                'verbose_name_plural': '\u0422\u0443\u0440\u0438\u0441\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='tour_booking',
            name='tourist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Tourist', verbose_name='\u0422\u0443\u0440\u0438\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Tour_type', verbose_name='\u0422\u0438\u043f \u0442\u0443\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='recource',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Tour', verbose_name='\u0412\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0439 \u0442\u0443\u0440'),
        ),
        migrations.AddField(
            model_name='recource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Recource_type', verbose_name='\u0422\u0438\u043f \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Region', verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d'),
        ),
    ]
