# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_booking',
            old_name='mobile_phone',
            new_name='phone_number',
        ),
    ]
