# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043c\u0435\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='message',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u041f\u0440\u0438\u0447\u0438\u043d\u0430 \u043e\u0442\u043c\u0435\u043d\u044b'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Manager', verbose_name='\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Tour', verbose_name='\u0412\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0439 \u0442\u0443\u0440'),
        ),
    ]
