# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-03 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='photo',
        ),
    ]
