# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_auto_20171111_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocution',
            options={'verbose_name': '\u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u041e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='allocution_type',
            options={'verbose_name': '\u0442\u0438\u043f \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f', 'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0439'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '\u0433\u043e\u0440\u043e\u0434', 'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '\u0441\u0442\u0440\u0430\u043d\u0430', 'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u044b'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': '\u0433\u043e\u0441\u0442\u0438\u043d\u0438\u0446\u0430', 'verbose_name_plural': '\u0413\u043e\u0441\u0442\u0438\u043d\u0438\u0446\u044b'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': '\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440', 'verbose_name_plural': '\u041c\u0435\u043d\u0435\u0434\u0436\u0435\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '\u0440\u0435\u0433\u0438\u043e\u043d', 'verbose_name_plural': '\u0420\u0435\u0433\u0438\u043e\u043d\u044b'},
        ),
        migrations.AlterModelOptions(
            name='tour_booking',
            options={'verbose_name': '\u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0442\u0443\u0440\u0430', 'verbose_name_plural': '\u0411\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u0442\u0443\u0440\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='tour_type',
            options={'verbose_name': '\u0442\u0438\u043f \u0442\u0443\u0440\u0430', 'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0442\u0443\u0440\u0430'},
        ),
        migrations.AlterModelOptions(
            name='tourist',
            options={'verbose_name': '\u0442\u0443\u0440\u0438\u0441\u0442', 'verbose_name_plural': '\u0422\u0443\u0440\u0438\u0441\u0442\u044b'},
        ),
    ]
