# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_remove_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(blank=True, default=123, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0437\u0430 \u0434\u0435\u043d\u044c \u0441 \u0447\u0435\u043b\u043e\u0432\u0435\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tour',
            name='hotel',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ManyToManyField(blank=True, null=True, to='Travel.Hotel', verbose_name='\u041e\u0442\u0435\u043b\u044c'),
        ),
    ]
