# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_auto_20171012_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
