# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_auto_20171118_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recource',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='recource',
            name='type',
        ),
        migrations.DeleteModel(
            name='Recource',
        ),
        migrations.DeleteModel(
            name='RecourceType',
        ),
    ]
