# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-04 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_tourbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='preference',
            field=models.TextField(null=True, verbose_name='\u041f\u0440\u0435\u0434\u043f\u043e\u0447\u0442\u0435\u043d\u0438\u0435'),
        ),
    ]
