# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_auto_20171012_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='recource',
            name='firstname',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='recource',
            name='lastname',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='recource',
            name='patronymic',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='recource',
            name='tourist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Travel.Tourist', verbose_name='\u0422\u0443\u0440\u0438\u0441\u0442'),
        ),
    ]
