# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0005_remove_hotel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocution',
            name='tourist_username',
        ),
        migrations.AlterField(
            model_name='allocution',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='allocution',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
    ]
