# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0005_auto_20171004_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u0422\u0438\u043f'),
        ),
    ]
