# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0006_auto_20171105_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocution',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='allocution',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='allocution',
            name='patronymic',
            field=models.CharField(max_length=20, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
