# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0006_auto_20171004_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('address', models.TextField(verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('comfort', models.IntegerField(max_length=5, verbose_name='\u0417\u0432\u0435\u0437\u0434')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Travel.City', verbose_name='\u0413\u043e\u0440\u043e\u0434')),
            ],
        ),
    ]
