# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0008_tourbooking_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='comfort',
            field=models.IntegerField(max_length=1, verbose_name='\u0417\u0432\u0435\u0437\u0434'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435'),
        ),
    ]
