# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0008_auto_20171105_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '\u0433\u043e\u0440\u043e\u0434', 'verbose_name_plural': '\u0433\u043e\u0440\u043e\u0434\u0430'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '\u0441\u0442\u0440\u0430\u043d\u0430', 'verbose_name_plural': '\u0441\u0442\u0440\u0430\u043d\u044b'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': '\u043e\u0442\u0435\u043b\u044c', 'verbose_name_plural': '\u043e\u0442\u0435\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '\u0440\u0435\u0433\u0438\u043e\u043d', 'verbose_name_plural': '\u0440\u0435\u0433\u0438\u043e\u043d\u044b'},
        ),
        migrations.AlterModelOptions(
            name='tour_booking',
            options={'verbose_name': '\u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0442\u0443\u0440\u0430', 'verbose_name_plural': '\u0431\u0440\u043e\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u0442\u0443\u0440\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='type_of_tour',
            options={'verbose_name': '\u0442\u0438\u043f \u0442\u0443\u0440\u0430', 'verbose_name_plural': '\u0442\u0438\u043f\u044b \u0442\u0443\u0440\u0430'},
        ),
        migrations.AlterField(
            model_name='allocution',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
