# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0009_auto_20171008_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(default=' ', max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u0443\u0440\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='comfort',
            field=models.IntegerField(verbose_name='\u0417\u0432\u0435\u0437\u0434'),
        ),
    ]
