# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0010_auto_20171009_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Tour', verbose_name='\u0412\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0439 \u0442\u0443\u0440'),
        ),
    ]
