# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0011_tourist_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Travel.Hotel', verbose_name='\u041e\u0442\u0435\u043b\u044c'),
        ),
    ]
