# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0012_auto_20171010_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='tour',
        ),
    ]
