# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0013_remove_tourist_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='tourist',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tourist',
            field=models.ManyToManyField(null=True, to='Travel.Tourist', verbose_name='\u0422\u0443\u0440\u0438\u0441\u0442'),
        ),
    ]
