# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0016_auto_20171106_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='hotel_price',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440'),
        ),
    ]
