# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0018_auto_20171106_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_price',
            field=models.PositiveSmallIntegerField(blank=True, default=1200, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_price',
            field=models.PositiveSmallIntegerField(default=12000, verbose_name='\u0426\u0435\u043d\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='comfort',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='\u041a\u043e\u043c\u0444\u043e\u0440\u0442'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='days',
            field=models.PositiveSmallIntegerField(verbose_name='\u0414\u043d\u0435\u0439'),
        ),
    ]
