# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0019_auto_20171106_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='hotel_price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_price',
            field=models.PositiveSmallIntegerField(blank=True, default=1500, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440'),
            preserve_default=False,
        ),
    ]
