# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0022_auto_20171107_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='hotel_price',
        ),
    ]
