# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0023_remove_tour_hotel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(verbose_name='\u0414\u043d\u0435\u0439')),
                ('sale', models.SmallIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='days',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_price',
            field=models.PositiveSmallIntegerField(default=1500, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ManyToManyField(blank=True, to='Travel.Hotel', verbose_name='\u041e\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='order',
            name='hotel_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Travel.Hotel', verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AddField(
            model_name='order',
            name='tour_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Travel.Tour', verbose_name='\u0426\u0435\u043d\u0430 \u0442\u0443\u0440\u0430'),
        ),
    ]
