# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0024_auto_20171107_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u0437\u0430\u043a\u0430\u0437', 'verbose_name_plural': '\u0437\u0430\u043a\u0430\u0437\u044b'},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='tour_price',
            field=models.PositiveSmallIntegerField(default=1200, verbose_name='\u0426\u0435\u043d\u0430'),
            preserve_default=False,
        ),
    ]
