# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0026_auto_20171107_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hotel_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tour_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_price',
        ),
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.PositiveSmallIntegerField(default=1500, verbose_name='\u0414\u043d\u0435\u0439'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ManyToManyField(blank=True, null=True, to='Travel.Hotel', verbose_name='\u041e\u0442\u0435\u043b\u044c'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
