# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0027_auto_20171107_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotel_price',
            field=models.PositiveSmallIntegerField(blank=True, default=1500, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tour',
            name='hotel',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Travel.Hotel', verbose_name='\u041e\u0442\u0435\u043b\u044c'),
        ),
    ]
