# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0028_auto_20171107_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='sale',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='comfort',
            field=models.PositiveIntegerField(default=1, verbose_name='\u041a\u043e\u043c\u0444\u043e\u0440\u0442'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='days',
            field=models.PositiveIntegerField(verbose_name='\u0414\u043d\u0435\u0439'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_price',
            field=models.PositiveIntegerField(verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
