# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0032_auto_20171109_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0442\u0443\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043d\u043e\u043c\u0435\u0440'),
        ),
    ]
